project:
  type: website
  output-dir: docs
resources: 
  - lrjohnsonCV.pdf
  - paul-cv.pdf
  - STS822.pdf
website:
  title: "QED Lab @ VT"
  description: "Quantitative Ecological Dynamics @ Virginia Tech"

  navbar:
    background: dark
    right:
      - text: "Home"
        href: index.html
      - text: "People"
        menu:
          - text: "PI: Dr. LR Johnson"
            href: leahJ.html
          - text: "Current Members"
            href: people_current.html
          - text: "Lab Alumni"
            href: people_alumni.html
      - text: "Research"
        menu:
          - text: "Research Areas"
            href: research.html
          - text: "VectorBiTE RCN and VectorByte"
            href: VB.html
      - text: "Publications"
        href: publications.html
      - text: "News/Blog"
        href: news.html
      - text: "Opportunities"
        href: opps.html
      - icon: fa fa-twitter
        href: https://twitter.com/QEDlab
    search: true




format:
  html:
    page-layout: full
    column: screen-inset
    theme:
      - united
      - custom.scss
    toc: true

editor: visual

